name: Test

on:
  push:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        php-version: ['8.1']
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Setup
      run: composer install --prefer-dist --no-suggest

    - name: Run tests
      run: composer run-script test
